### ISSUE TITLE
[design] 왼쪽 사이드바 구분선 더 명확하게

### ISSUE THREAD

**Issue by kimminkyeu** [Kernel360/F2-BAGUNI#694]
## 제안 (의견 주세요)

현재 사용한 색상이 시각적으로 사이드바 구분이 잘 안됨.
- 왼쪽 사이드바가 크기 조절이 가능하다는게 잘 표시가 안되는데
   - 이 부분이 시각적으로 조금 더 보였으면 좋겠습니다.
<img width="300px" src="https://github.com/user-attachments/assets/b1679515-a9b0-4b36-8856-832b153deb07" />
<img width="300px" src="https://github.com/user-attachments/assets/df519b9b-d00a-47c7-9b8c-ed8ae209edde" />

1. 왼쪽 사이드바의 색이 더 어둡게 하고, 희미하게 그림자를 주면 더 좋을 것 같아요 (`색은 오른쪽 gold 색상 채도와 통일, 명도만 변경`)
2. 마우스를 올렸을 때 그림자가 두꺼워졌으면 좋겠어요.

**Comment by obvoso** [comment]
노션처럼 사이드바 백그라운드 색을 어둡게하고, 오른쪽에 드롭쉐도우 + 호버시 쉐도우 짙게 스타일 변경만 말씀하시는거죠?

사이드바 너비를 조절할 수 있다는 걸 시각적으로 나타기위해 그림자를 넣으라는 건가요
아님 그림자 + 너비조절 기능은 아이콘 추가 등으로 개선하자는건가요..?

**Comment by kimminkyeu** [comment]
@obvoso 네 아이콘 추가가 아니고 시각적으로만 구분해도 될 것 같습니다.

**Comment by kimminkyeu** [comment]
### Before
![1](https://github.com/user-attachments/assets/dd41f6b5-a630-429f-ae26-a713940e1fb1)
### After
![2](https://github.com/user-attachments/assets/6e5961b4-8ed2-4e7b-a277-40049558d3a5)
### Color Hex (사이드바, 그림자, 오른쪽 메인 순서)
![3](https://github.com/user-attachments/assets/a57029a1-e04b-46bc-9476-98ed51abc0e3)

@obvoso @dmdgpdi 이정도면 어떨까요?

**Comment by kimminkyeu** [comment]
일단 위에 올려드린 색상으로 (그림자 포함) 기본적으로 뜨고,  호버시 그림자 명도가 살짝만 어둡게 되면 될 듯험
