### ISSUE TITLE
[feat] 배포 시 swagger 파일 정적으로 저장하도록 구현

### ISSUE THREAD

**Issue by Gyaak** [Kernel360/F2-BAGUNI#700]
## 기능

배포시 `/api-docs`에서 제공되는 json파일을 서버에 정적으로 저장하도록 구현
그리고 `/swagger-ui/index.html` 경로는 막도록 변경

**Comment by kimminkyeu** [comment]
Swagger를 별도 서버로 분리하지 않기로 결정했습니다.
이유는 내부 서버 모듈간에 swagger 표시는 필요 없다고 판단했기 때문이고,
이 설정을 하려면 내부 구현이 너무 복잡해지기 때문.

위 결정에 따라 해당 이슈는 종료합니다.
