### ISSUE TITLE
[bug] 검색 후 렌더링 도중 검색어 제거 시 빈 화면 나타나는 문제

### ISSUE THREAD

**Issue by sangwonsheep** [Kernel360/F2-BAGUNI#769]
## Describe the bug
1. 검색 후 화면이 렌더링 되는 시간에 검색어를 모두 지움. -> 공백이 없는 빈 문자열인 상태
2. 검색어가 없으면 모든 픽이 조회되어야 하는데 아무것도 나타나지 않는 문제 발생
3. 공백이 없는 빈 문자열인 상태에서 엔터를 입력하여도 아무것도 나타나지 않음
4. 스페이스바 입력 시 모든 픽 조회됨.

## 원하는 이상적인 동작
- 렌더링 도중 검색어를 제거한 경우 모든 픽이 조회되어야 함.
- 그렇지 않더라도, 엔터 입력 시 모든 픽이 조회되어야 함.

### Screenshots
https://github.com/user-attachments/assets/21653fee-294e-4d9e-84b8-6d4c7da1057a

**Comment by obvoso** [comment]
저는 재연이 안되는 거 같은데 회의 끝나고 올라오셔서 재연해주실 수 있으신가요?

**Comment by sangwonsheep** [comment]
1. 검색창에 | 입력
2. 바로 | 삭제

이 순서로 해보시겠어요? 
검색어 옆에 돋보기가 랜더링 표시 중일 때 검색어를 지우면 발생합니다
<img width="212" alt="스크린샷 2024-12-12 오후 3 01 00" src="https://github.com/user-attachments/assets/44c15ec1-ae2c-4155-be9d-58cafd6b8fbb" />
