### ISSUE TITLE
[bug] 현재 위치한 폴더에서 마이페이지 클릭 시 포커싱이 유지되는 문제

### ISSUE THREAD

**Issue by sangwonsheep** [Kernel360/F2-BAGUNI#783]
## Describe the bug
1. 현재 위치한 폴더에서 마이페이지 클릭 시 현재 폴더의 포커싱이 유지되는 문제
2. 로그아웃 버튼 위치 조정이 필요할 것 같습니다.
  - 내 계정 정보와 너무 붙어 있는 것 같습니다.

## 원하는 이상적인 동작
- 마이페이지에 포커싱이 되어야 함

### Screenshots
![스크린샷 2024-12-13 오후 5 39 22](https://github.com/user-attachments/assets/864261e2-719a-42a8-b949-8ed88c6adbf0)

**Comment by sangwonsheep** [comment]
@dmdgpdi 
![image](https://github.com/user-attachments/assets/7619b8a2-f346-432b-9999-e3257f3270cf)
![image](https://github.com/user-attachments/assets/0e60d55e-c1d2-4ef8-aa63-6d7ee7b29fa3)
기본 폴더에서 마이페이지 클릭 시에는 포커싱 처리가 제대로 되지만 사용자가 생성한 폴더에서는 포커싱 처리가 제대로 되지 않습니다.ㅠㅠ

**Comment by dmdgpdi** [comment]
@sangwonsheep 감사합니다! 수정할게요!
