### ISSUE TITLE
[bug] 한글 태그 입력 오류

### ISSUE THREAD

**Issue by kimminkyeu** [Kernel360/F2-BAGUNI#825]
## Describe the bug

태그 한글로 입력 시에 서버 에러 발생 
![image](https://github.com/user-attachments/assets/bd55f2b9-1e1e-49a5-83bb-e26e0f728d71)

**Comment by sangwonsheep** [comment]
![스크린샷 2024-12-17 오후 2 18 19](https://github.com/user-attachments/assets/425dd6e8-4bc6-475a-a6ab-18f2f41ba80a)
