### ISSUE TITLE
[bug] access_token 만료 시 로그인 페이지로 이동 필요

### ISSUE THREAD

**Issue by sangwonsheep** [Kernel360/F2-BAGUNI#850]
## Describe the bug
1. 픽 이동 시 이동이 되지 않는 문제가 발생했었음.
2. 원인을 찾아본 결과 : access_token이 만료되었음.
3. access_token이 만료되었는데 현재 화면이 계속 유지되는 문제가 있음.

## 원하는 이상적인 동작
- access_token이 만료된 상태에서 api 호출이 하나라도 일어나거나 동작이 발생하면 로그인 화면으로 이동

### Screenshots
<img width="952" alt="스크린샷 2024-12-20 오후 12 51 14" src="https://github.com/user-attachments/assets/4ccf9fc8-7a41-4e8d-85c0-20f52455a787" />

<img width="623" alt="스크린샷 2024-12-20 오후 12 51 36" src="https://github.com/user-attachments/assets/8bbb42e2-c857-4b5f-ad69-7d1da92bb092" />

**Comment by kimminkyeu** [comment]
#857 이슈 생성하였으므로 버그 리포트 닫습니다.
