### ISSUE TITLE
[fix] 서버 내 도커 이미지 정리 과정에서 오류 발생 

### ISSUE THREAD

**Issue by kimminkyeu** [Kernel360/F2-BAGUNI#865]
## 기능
![image](https://github.com/user-attachments/assets/e3b34055-c27f-407d-9ec6-fca1b30f8bac)
### 문제
- 코어 모듈 수정 시 api, batch, ranking 모듈이 모두 재배포된다.
- 이때, `docker image prune` 이 각 github action에서 동시에 실행됨
- 이미 실행중인 명령어로 인해 도커 데몬이 `exit 1`되고, 깃헙 액션 프로세스가 오류로 간주되어 종료함.
### 해결 방안
- 깃헙 액션 스크립트에서 이미지 정리 명령어를 제거
- 대신, 서버 내에서 crontab으로 정기적으로 이미지 정리 수행

**Comment by sangwonsheep** [comment]
crontab으로 특정 주기마다 삭제하는 것으로 이해했습니다.

1. 현재 사용하고 있는 이미지만 제외하고 사용하지 않는 이미지만 지우는 것으로 이해하면 될까요?
2. 이미지가 생성된 후 24시간이 지나면 이미지를 삭제한다고 하면 사용 중인 이미지도 삭제되는지 궁금합니다.
