### ISSUE TITLE
[feat] 미분류 즉시 담기 API + 픽 중복 저장 (~이번주 주말)

### ISSUE THREAD

**Issue by kimminkyeu** [Kernel360/F2-BAGUNI#870]
## 기능
- :warning: 주말까지 작업, 다음주 부터 승태님 작업 시작
- 기존 api는 폴더 정보 + 링크 정보를 획득해야 담기가 가능
- 익스텐션 `즉시 담기` 기능을 위해선...
   1. `linkInfo` 없이 url만 입력
   2. 대상 폴더 / 대상 순서 정보 생략

**Comment by sangwonsheep** [comment]
픽 중복 허용까지 같이 작업해야 합니다.

**Comment by sangwonsheep** [comment]
현재 Jsoup으로 og:image만 가져옵니다.
og:title, og:description도 같이 가져오도록 변경해야 합니다.

**Comment by sangwonsheep** [comment]
기존에 존재하는 링크 테이블의 데이터는 수정하지 않도록 변경할 예정입니다.
스케줄링 시에 변경되도록 할 예정입니다.

**Comment by sangwonsheep** [comment]
@dmdgpdi 
### 상황 설명
승태님 익스텐션에서 제목 데이터 어떤 방식으로 가져오는지 알 수 있을까요?

요청으로 url만 보내주신다고 가정하고 로직을 짜고 있었습니다.
jsoup을 이용하여 `<title>`에 있는 데이터를 가져오고자 했었습니다.
근데 모든 사이트에 `<title>` 태그가 있는게 아니었네요....?

라인 테크 블로그의 경우 `<title>` 태그가 없어서 어떻게 넣는거지 하고 네트워크를 3g로 하고 확인해보았습니다.
바로 타이틀이 정해지는게 아니라 동적으로 타이틀이 바뀌게끔 되어 있는 걸 확인했습니다.

### 결론
혹시 가능하시다면, 익스텐션에서 미분류로 보낼 때 `url, title`을 같이 보내주실 수 있을까요?

### 라인 블로그
https://techblog.lycorp.co.jp/ko
