### ISSUE TITLE
[bug] 잘못된 이미지 url일 때 엑스박스가 표기되는 문제

### ISSUE THREAD

**Issue by dmdgpdi** [Kernel360/F2-BAGUNI#873]
## Describe the bug
image url이 올바르지 않을 때 엑스박스가 생성됩니다.

<img width="710" alt="스크린샷 2024-12-26 오전 11 50 26" src="https://github.com/user-attachments/assets/6b16bb72-05bf-40c4-a9dd-7777831027b5" />

## 원하는 이상적인 동작
엑스박스가 아닌 default image가 보이게 합니다.

**Comment by sangwonsheep** [comment]
백엔드 측에서 imageurl을 파싱해서 넘겨드리는 방향으로 진행하겠습니다.

### image url 예시
`og:image`가 절대 경로가 아닌 상대 경로로 되어 있는 경우가 있습니다.
- 예시 1 :  /og-image.png
- 참고 사이트 : https://blog.dongholab.com/about
- 예시 2 : /img/apple_icon.png
- 참고 사이트 : https://namu.wiki/w/%ED%98%91%EC%97%85%ED%88%B4

현재 로직에는 위 링크 뒤에 붙이는 형태로 되어 있습니다.
이렇게 image url을 불러오게 된다면, 올바르지 않은 image url이므로 엑스박스가 나타나게 됩니다.
- 현재 로직 : https://blog.dongholab.com/about/og-image.png
- 또 다른 예시 : https://namu.wiki/w/%ED%98%91%EC%97%85%ED%88%B4/img/apple_icon.png

올바른 이미지 경로를 백엔드에서 파싱해서 넘겨주면 될 것 같습니다.
`og:image`가 상대 경로로 되어 있는 경우, .com 뒤에 og:image를 붙이는 방향으로 로직을 수정해야 할 것 같습니다.
- 올바른 이미지 경로 : https://blog.dongholab.com/og-image.png
- 또 다른 예시 : https://namu.wiki/img/apple_icon.png

**Comment by dmdgpdi** [comment]
@sangwonsheep 감사합니다! 
대면으로 이야기 나눈 대로 올바른 URL이여도 접근이 거부당하거나, 자원이 없는 경우가 있으므로, 프론트에서도 막았습니다!
